language: go

sudo: required
dist: trusty

services:
  - docker

env:
 - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

go:
  - '1.11.x'
  - '1.x'

install:
  - go build -o sharkey-server -v ./cmd/sharkey-server
  - go build -o sharkey-client -v ./cmd/sharkey-client
  - docker build -t server:latest -f Dockerfile .
  - docker build -t client:latest -f DockerfileClientTest .

script:
  # Unit tests
  - go test -v ./...
  # Integration tests
  - ./integration-test.sh
