language: go

sudo: required
dist: trusty

services:
  - docker

go:
  - '1.11.x'
  - '1.x'

install:
  - go build -o sharkey-server -v ./server
  - go build -o sharkey-client -v ./client
  - docker build -t server:latest -f Dockerfile .
  - docker build -t client:latest -f DockerfileClientTest .

script:
  # Unit tests
  - go test -v ./server
  - go test -v ./client
  # Integration tests
  - ./integration-test.sh
