language: go

services:
  - mysql
  - docker

env:
 - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

go:
  - '1.x'


before_install:
  - mysql -e 'CREATE DATABASE sharkey_test;'

install: skip

script:
  # Docker images
  - docker build -t server:latest -f Dockerfile .
  - docker build -t client:latest -f DockerfileClientTest .
  # build binaries
  - go build -v -o sharkey-server ./cmd/sharkey-server/
  - go build -v -o sharkey-client ./cmd/sharkey-client/
  # Unit tests
  - go test -v ./...
  # Integration tests
  - ./integration-test.sh
